name: Build Pelican Site

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Install necessary packages
      - run: sudo apt-get update && sudo apt-get install -y python3 python3-pip pelican make

      # Install Python dependencies from requirements.txt
      - run: pip3 install -r requirements.txt

      # Build the Pelican site
      - run: make publish

      # (Optional) Any additional steps like PDF rendering
